### ISSUE TITLE
Klarna Upstream now supports purchase_amount which includes minor units

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#1]
<klarna-placement
    data-id="1212345556"
    data-purchase_amount="10000"
></klarna-placement>

Please note the above use of 'purchase_amount' which is micro units, ie. 100 USD == 10000

Use of 'total_amount' with dollar/cent values, ie. 100 USD == 100.00 is still backwards compatible.

**Comment by NiklasHogefjord** [comment]
Fixed. Minor units confirmed to be used in v1.0.0+
