### ISSUE TITLE
Problem with changing location using filter

### ISSUE THREAD

**Issue by degborta** [krokedil/klarna-onsite-messaging-for-woocommerce#11]
I am having some issues, running Flatsome with a custom layout product page where I have manually added a hook called: flatsome_custom_single_product_2 where I want to output the placement that I have configured.

I have tried the same placement_id in the cart and it works, so that is not the issue.

Here is the code:
add_filter( 'klarna_onsite_messaging_product_target', 'change_klarna_onsite_messaging_product_location' );
function change_klarna_onsite_messaging_product_location( $location ) {
    return 'flatsome_custom_single_product_2';
}

But nothing shows.

If I do this instead, this text shows up correctly:
add_action( 'flatsome_custom_single_product_2', 'testing', 5 );
function testing() {
  echo "TESTING";
}

Am I doing something wrong?

**Comment by degborta** [comment]
Just did this instead:

`add_action( 'flatsome_custom_single_product_2', 'kco_onsite_messaging',5);
function kco_onsite_messaging() {
  $kco = new Klarna_OnSite_Messaging_Product_Page();
  $kco->add_iframe();
}
`

**Comment by MichaelBengtsson** [comment]
Thank you @degborta. It seems that in one of the latest updates we changed something that caused these filters to run to early. I have a fix for this now that will be released with the new version.
