### ISSUE TITLE
Addon breaks woocommerce variation product pages

### ISSUE THREAD

**Issue by k3nsai** [krokedil/klarna-onsite-messaging-for-woocommerce#14]
When enabling the addon via the woocommerce payment plugin, this part of the klarna-onsite-messaging.js (according to console):

```
update_total: function (variation) {
      document.getElementsByTagName('klarna-placement') [0].setAttribute('data-total_amount', variation.display_price);
      klarna_onsite_messaging.update_iframe();
    }
```
causes the following error on woocommerce and freezes the selection of variation products:

_TypeError: document.getElementsByTagName(...)[0] is undefined_

Any ideas why this is happening? Also no banners appear anywhere on the site, which is probably because this is not working.

**Comment by MichaelBengtsson** [comment]
Sorry for the late reply, but this should be fixed since several versions back. If you are still having this issue, then please reopen this issue.

**Comment by k3nsai** [comment]
12 months later is hardly considered a late reply...
FWIW, I have stopped using Klarna because of such issues and lack of replies/support for such critical issues.
