### ISSUE TITLE
Merchants installing the OSM plugin are not getting the most recent release

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#15]
When a merchant installs the KOSM Woo plugin (via Klarna Add-ons page), they are getting Version 1.0.1, not latest version (Version 1.0.4) (per https://github.com/krokedil/klarna-onsite-messaging-for-woocommerce/releases)

**Comment by NiklasHogefjord** [comment]
Fixed now. Manually updated the latest version of the plugin. Will develop an automated flow for this in the upcoming month.
