### ISSUE TITLE
Enhancement - support Klarna playground for OSM

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#16]

**Comment by kristibarbosky** [comment]
new endpoint, e.g.:
<script async src="https://us-library.playground.klarnaservices.com/merchant.js

**Comment by NiklasHogefjord** [comment]
Fixed in https://github.com/krokedil/klarna-onsite-messaging-for-woocommerce/releases/tag/1.2.0
