### ISSUE TITLE
Additional CSS code requested for placement

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#2]
A merchant using Klarna On-Site Marketing has requested to add additional CSS code ( margin: 0px auto 15px;) per example below: So, the Klarna is centered on responsive layout.  Or if that isn't desired for the plugin, could you provide documentation for how the merchant could customize this themselves if that is more appropriate?

<klarna-placement data-id="*****" data-total_amount="100.00" style="display: block;max-width: 350px;max-height: 100px;width: 100%;position: relative;overflow: hidden; margin: 0px auto 15px;"

**Comment by MichaelBengtsson** [comment]
Fixed in f8fbe0bf250d5befe929ad836cf765527fd9b860
