### ISSUE TITLE
Says not compatible with Wordpress 5.5.3

### ISSUE THREAD

**Issue by broksonic21** [krokedil/klarna-onsite-messaging-for-woocommerce#37]
The plugin currently is listed as only working up to 5.5.1

Any concerns using 5.5.3?

<img width="747" alt="image" src="https://user-images.githubusercontent.com/24306571/100099806-e9738480-2e2d-11eb-9bff-5839833c6cc7.png">

**Comment by MichaelBengtsson** [comment]
Hi @broksonic21 5.5.3 should work, it was simply an oversight when pushing a new release. It will be fixed for the next version

**Comment by MichaelBengtsson** [comment]
This has been fixed in the latest version
