### ISSUE TITLE
Handle blank price

### ISSUE THREAD

**Issue by devonto** [krokedil/klarna-onsite-messaging-for-woocommerce#40]
For complex products which `wc_get_price_to_display()` returns a blank/zero price (such as a customisable gift card product), please add a clause to check for this in the `add_iframe` function.

PHP warnings are being produced as follows:

`PHP message: PHP Warning:  A non-numeric value encountered in /site/wp-content/plugins/klarna-onsite-messaging-for-woocommerce/classes/class-klarna-onsite-messaging-product-page.php on line 121`

Changing line 121 from:

`$price = wc_get_price_to_display( $product ) * 100;`

to:

```
$price = wc_get_price_to_display( $product );
if(is_numeric($price)) $price = $price * 100;
```
Appears to work and I have applied the change manually on two sites for the past three updates.

**Comment by MichaelBengtsson** [comment]
@devonto Sorry for the late reply. We will get this added for the next version of the plugin
