### ISSUE TITLE
Support for WooCommerce Product Bundles

### ISSUE THREAD

**Issue by broksonic21** [krokedil/klarna-onsite-messaging-for-woocommerce#41]
Right now if you use WooCommerce's suggested product bundles plugin: https://docs.woocommerce.com/document/bundles/, OSM doesn't work

That's because add_iframe function calls:

```
		if ( $product->is_type( 'variable' ) ) {
			$price = $product->get_variation_price( 'min' ) * 100;
		} else {
			$price = wc_get_price_to_display( $product ) * 100;
		}
```

and wc_get_price_to_display returns 0 for bundles.

Can you get support in?

**Comment by broksonic21** [comment]
Or is there a way to get OSM to show even if 0-priced?

**Comment by broksonic21** [comment]
Also here: https://wordpress.org/support/topic/woocommerce-product-bundles-incompatible/#new-topic-0

**Comment by a-larsson** [comment]
Hi @broksonic21 

We have created an internal ticket to look at this and to create support for it. I can not tell you when this will be done but hopefully in a couple of weeks.
