### ISSUE TITLE
Deprectated function call

### ISSUE THREAD

**Issue by zreak** [krokedil/klarna-onsite-messaging-for-woocommerce#42]
Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /plugins/klarna-onsite-messaging-for-woocommerce-master/includes/plugin_update_check.php on line 830

**Comment by zreak** [comment]
Server architecture | Linux 4.15.0-143-generic x86_64
Web server | nginx/1.19.9
PHP version | 7.4.16 (Supports 64bit values)

**Comment by MichaelBengtsson** [comment]
Hi Zreak,

Sadly this is not part of "our" code but the thing we use for automated updates. We will however look at the latest version of this and see if there is an update for it, or get in contact with the developer of that to see if they can solve it.
