### ISSUE TITLE
Documentation for Klarna On-Site Marketing Woo plugin

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#5]
When time permits, we should create documentation for this plugin.  Can that documentation include that the KOSM is displayed within the Woo  product meta information.  If that section is hidden, the KOSM would also be hidden (which was discovered by a merchant).

**Comment by kristibarbosky** [comment]
Need to document that we don't support front end CSS customizations; document switching actions (PHP)

**Comment by kristibarbosky** [comment]
need to explain how to debug, e.g. that price is inserted into the page when page is loaded so price data is not available in HTML source, but can be seen by inspecting the element

**Comment by kristibarbosky** [comment]
https://docs.krokedil.com/article/259-klarna-on-site-messaging

**Comment by kristibarbosky** [comment]
please document Woo widgets functionality

**Comment by NiklasHogefjord** [comment]
Documented here: https://docs.krokedil.com/article/259-klarna-on-site-messaging#h-H2_4
