### ISSUE TITLE
support currency switchers

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#6]
When a merchant uses a currency switcher, could this upstream plugin handle only adding the placement_id when the currency of the product matches the configured KP markets, e.g. for a US based store, KP likely only applies to USD orders, so the KOSM shouldn't be displayed for EUR orders.  Currently the placement is always displayed in my test store for this scenario. (Dependancy: GO-2863)

**Comment by NiklasHogefjord** [comment]
That is a good idea @kristibarbosky. We will implement this and also go through the other issues so we can release a new version with an updated name of the plugin.

**Comment by kristibarbosky** [comment]
To display different OSM for different currencies, this plugin will have to map the selected currency to a locale as OSM code does not have a currency parameter, which is not ideal, so perhaps this should be a configurable option. what locale should be used for EUR which supports multiple locales?


<script 
  async 
  src="https://eu-library.klarnaservices.com/lib.js"
  data-client-id="123457-9639-54f2-9250-4537643777be0"
></script>

<klarna-placement
  data-key="credit-promotion-small"
  data-locale="en-SE"
  data-purchase-amount="34900"
></klarna-placement>

**Comment by MichaelBengtsson** [comment]
Support added in 07ad8143a5c9db17e9c01f4daf04cb990db88f70 but still under development
