### ISSUE TITLE
load JS async

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-onsite-messaging-for-woocommerce#7]
If there are any issues with the Klarna On-Site Marketing code, we don't want to cause any slowness to the merchant's site, so can the klarnaservices JS file be loaded async?

**Comment by kristibarbosky** [comment]
Kristi researching more details regarding this issue (per chat with Michael today).

**Comment by kristibarbosky** [comment]
Per discussion today, I've created PREP-1678 to determine if we could simulate the KOSM outage in order to test this issue further to determine if the plugin could even possibly be changed to improve this.

If there was another outage though, merchants could deactivate the Woo KOSM plugin to avoid any impact.

**Comment by NiklasHogefjord** [comment]
Klarna JS files are now loaded async:

![image](https://user-images.githubusercontent.com/985946/75820825-5bd29f00-5d9d-11ea-80e8-8e29649c4efa.png)

OK to close this @kristibarbosky ?

**Comment by kristibarbosky** [comment]
Thanks so much @NiklasHogefjord  - yes, happy to close now!
